version: '3.8'

services:
  # Layanan Database PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: cbt_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cbt_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  # Layanan Zookeeper (Dibutuhkan oleh Kafka)
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    container_name: cbt_zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      KAFKA_JVM_PERFORMANCE_OPTS: "-server -XX:ParallelGCThreads=1 -Xms512M -Xmx512M -XX:-UseContainerSupport"
    ports:
      - "2181:2181"
    restart: unless-stopped

  # Layanan Kafka Broker
  kafka:
    image: confluentinc/cp-kafka:7.3.0
    container_name: cbt_kafka
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_JVM_PERFORMANCE_OPTS: "-server -XX:ParallelGCThreads=1 -Xms512M -Xmx512M -XX:-UseContainerSupport"
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local